---
title: "audio_analysis"
author: "GabiK"
date: "5/20/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load required libraries
library(tidyverse)
library(ggplot2)
library(infer)
library(scales)
library(ggridges)
library(glue)
library(Rmisc)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")

#N.B. after installing new packages, re-start R before running the script
```
# RANDOMIZATION TEST: comparison of mean echolocation call latency per site
```{r}
#set seed for reproducible results
set.seed(42)
```
# Anklam
```{r}
anklam=read.csv("data/Anklam_call_latency.txt", header=F, sep="\t")
colnames(anklam)=c("videofile", "audiofile", "timefirstcall", "treatment")
anklam=na.omit(anklam)
head(anklam)

#time to first call in seconds on flash-off weeks
flash_off = anklam$timefirstcall[anklam$treatment=="flash off"]
summary(flash_off)
mean_flashoff = mean(flash_off) 
#time to first call in seconds on flash-on weeks
flash_on = anklam$timefirstcall[anklam$treatment=="flash on"]
summary(flash_on)
mean_flashon = mean(flash_on)
# observed difference in means
diff_means_obs = mean_flashoff-mean_flashon 

# Step 1: Bootstrapped distribution of differences
boot_means = anklam %>% 
  specify(timefirstcall ~ treatment) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))
boostrapped_confint = boot_means %>% get_confidence_interval()

boot_means %>% 
  visualize() + 
  shade_confidence_interval(boostrapped_confint,color = "#8bc5ed", fill = "#85d9d2")+
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  labs(title = "Bootstrapped distribution of differences in means in Anklam",
       x = "flash off - flash on", y = "Count",
       subtitle = "Red line shows observed difference; shaded area shows 95% confidence interval") 

# Step 2: Simulation with no difference between treatments
genre_diffs_null = anklam %>% 
  specify(timefirstcall ~ treatment) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 10000, type = "permute") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))

# Step 3: Check if observed difference fits in the 'null' world
genre_diffs_null %>% 
  visualize() + 
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  scale_y_continuous(labels = comma) +
  labs(x = "Simulated difference in average time till first call (flash off-flash on)", y = "Count", title = "Simulation-based null distribution of differences in means in Anklam", subtitle = "Red line shows observed difference") 

# Step 4: Calculate probability that observed difference could exist in 'null' world
genre_diffs_null %>% 
  get_p_value(obs_stat = diff_means_obs, direction = "both")
```
# Demmin
```{r}
demmin=read.csv("data/Demmin_call_latency.txt", header=F, sep="\t")
colnames(demmin)=c("videofile", "audiofile", "timefirstcall", "treatment")
demmin=na.omit(demmin)
head(demmin)

#time to first call in seconds on flash-off weeks
flash_off = demmin$timefirstcall[demmin$treatment=="flash off"]
summary(flash_off)
mean_flashoff = mean(flash_off) 
#time to first call in seconds on flash-on weeks
flash_on = demmin$timefirstcall[demmin$treatment=="flash on"]
summary(flash_on)
mean_flashon = mean(flash_on)
# observed difference in means
diff_means_obs = mean_flashoff-mean_flashon 

# Step 1: Bootstrapped distribution of differences
boot_means = demmin %>% 
  specify(timefirstcall ~ treatment) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))
boostrapped_confint = boot_means %>% get_confidence_interval()

boot_means %>% 
  visualize() + 
  shade_confidence_interval(boostrapped_confint,color = "#8bc5ed", fill = "#85d9d2")+
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  labs(title = "Bootstrapped distribution of differences in means in Demmin",
       x = "flash off - flash on", y = "Count",
       subtitle = "Red line shows observed difference; shaded area shows 95% confidence interval") 

# Step 2: Simulation with no difference between treatments
genre_diffs_null = demmin %>% 
  specify(timefirstcall ~ treatment) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 10000, type = "permute") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))

# Step 3: Check if observed difference fits in the 'null' world
genre_diffs_null %>% 
  visualize() + 
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  scale_y_continuous(labels = comma) +
  labs(x = "Simulated difference in average time till first call (flash off-flash on)", y = "Count", title = "Simulation-based null distribution of differences in means in Demmin", subtitle = "Red line shows observed difference") 

# Step 4: Calculate probability that observed difference could exist in 'null' world
genre_diffs_null %>% 
  get_p_value(obs_stat = diff_means_obs, direction = "both")
```
# Friedland
```{r}
friedland=read.csv("data/Friedland_call_latency.txt", header=F, sep="\t")
colnames(friedland)=c("videofile", "audiofile", "timefirstcall", "treatment")
friedland=na.omit(friedland)
head(friedland)

#time to first call in seconds on flash-off weeks
flash_off = friedland$timefirstcall[friedland$treatment=="flash off"]
summary(flash_off)
mean_flashoff = mean(flash_off) 
#time to first call in seconds on flash-on weeks
flash_on = friedland$timefirstcall[friedland$treatment=="flash on"]
summary(flash_on)
mean_flashon = mean(flash_on)
# observed difference in means
diff_means_obs = mean_flashoff-mean_flashon 

# Step 1: Bootstrapped distribution of differences
boot_means = friedland %>% 
  specify(timefirstcall ~ treatment) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))
boostrapped_confint = boot_means %>% get_confidence_interval()

boot_means %>% 
  visualize() + 
  shade_confidence_interval(boostrapped_confint,color = "#8bc5ed", fill = "#85d9d2")+
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  labs(title = "Bootstrapped distribution of differences in means in Friedland",
       x = "flash off - flash on", y = "Count",
       subtitle = "Red line shows observed difference; shaded area shows 95% confidence interval") 

# Step 2: Simulation with no difference between treatments
genre_diffs_null = friedland %>% 
  specify(timefirstcall ~ treatment) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 10000, type = "permute") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))

# Step 3: Check if observed difference fits in the 'null' world
genre_diffs_null %>% 
  visualize() + 
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  scale_y_continuous(labels = comma) +
  labs(x = "Simulated difference in average time till first call (flash off-flash on)", y = "Count", title = "Simulation-based null distribution of differences in means in Friedland", subtitle = "Red line shows observed difference") 

# Step 4: Calculate probability that observed difference could exist in 'null' world
genre_diffs_null %>% 
  get_p_value(obs_stat = diff_means_obs, direction = "both")
```
# Peenemuende
```{r}
peenemuende=read.csv("data/Peenemuende_call_latency.txt", header=F, sep="\t")
colnames(peenemuende)=c("videofile", "audiofile", "timefirstcall", "treatment")
peenemuende=na.omit(peenemuende)
head(peenemuende)

#time to first call in seconds on flash-off weeks
flash_off = peenemuende$timefirstcall[peenemuende$treatment=="flash off"]
summary(flash_off)
mean_flashoff = mean(flash_off) 
#time to first call in seconds on flash-on weeks
flash_on = peenemuende$timefirstcall[peenemuende$treatment=="flash on"]
summary(flash_on)
mean_flashon = mean(flash_on)
# observed difference in means
diff_means_obs = mean_flashoff-mean_flashon 

# Step 1: Bootstrapped distribution of differences
boot_means = peenemuende %>% 
  specify(timefirstcall ~ treatment) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))
boostrapped_confint = boot_means %>% get_confidence_interval()

boot_means %>% 
  visualize() + 
  shade_confidence_interval(boostrapped_confint,color = "#8bc5ed", fill = "#85d9d2")+
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  labs(title = "Bootstrapped distribution of differences in means in Peenemuende",
       x = "flash off - flash on", y = "Count",
       subtitle = "Red line shows observed difference; shaded area shows 95% confidence interval") 

# Step 2: Simulation with no difference between treatments
genre_diffs_null = peenemuende %>% 
  specify(timefirstcall ~ treatment) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 10000, type = "permute") %>% 
  calculate("diff in means", order = c("flash off", "flash on"))

# Step 3: Check if observed difference fits in the 'null' world
genre_diffs_null %>% 
  visualize() + 
  geom_vline(xintercept = diff_means_obs, size = 1, color = "#77002c") +
  scale_y_continuous(labels = comma) +
  labs(x = "Simulated difference in average time till first call (flash off-flash on)", y = "Count", title = "Simulation-based null distribution of differences in means in Peenemuende", subtitle = "Red line shows observed difference") 

# Step 4: Calculate probability that observed difference could exist in 'null' world
genre_diffs_null %>% 
  get_p_value(obs_stat = diff_means_obs, direction = "both")
```
# Create data frames for plotting
```{r}
anklam$site="Anklam"
demmin$site="Demmin"
friedland$site="Friedland"
peenemuende$site="Peenemuende"

merged=rbind(demmin,anklam,peenemuende,friedland)
merged2=merged %>%
  group_by(site,treatment) %>%
  add_count(name="samplesize") %>%
  mutate(treatment=fct_recode(treatment,
        "flash-off" = "flash off", "flash-on"="flash on")) %>% 
  mutate(samplesize = glue("{ treatment } \n (N={ samplesize })")) %>% 
  mutate(ms_time=timefirstcall*1000) #calculate echolocation call latency in ms
summary=
  merged2 %>% 
  group_by(site,samplesize) %>% 
  summarySE(measurevar="timefirstcall", groupvars = c("site","treatment")) %>% 
  mutate(samplesize = glue("{ treatment } \n (N={ N })"))
```
# Figure 3 in the manuscript
```{r}
final_plot=ggplot(data = merged2, 
            aes(y = ms_time, x = samplesize , fill = treatment)) +
  geom_flat_violin(position = position_nudge(x = 0.25, y = 0), alpha = .8) +
  geom_point(aes(y = ms_time, color =treatment), 
             position = position_jitter(width = .15), size = .5, alpha = 0.8) +
  geom_boxplot(width = .3, outlier.shape = NA, alpha = 0.5) +
  geom_point(data = summary, aes(x = samplesize, y = timefirstcall*1000), position =
               position_nudge(.25), colour = "black", inherit.aes = F)+
  geom_errorbar(data = summary, aes(x = samplesize, y = timefirstcall*1000, ymin = timefirstcall*1000-ci*1000, ymax = timefirstcall*1000+ci*1000), position = position_nudge(.25), colour = "black", width = 0.1, size = 0.7)+
  expand_limits(x = 1) +
  facet_wrap(~site, scales="free")+
  coord_flip()+
  labs(x="", y="latency of first call after camera trigger (ms)")+
    scale_color_manual(values=c("#4A6FE3", "#D33F6A"))+
  scale_fill_manual(values=c("#4A6FE3", "#D33F6A"))+
  scale_x_discrete(expand=c(0,0.25))+
  theme_bw() +
  theme(legend.position = "none", axis.text.y = element_text(hjust=0.5))
final_plot
```
# Save high resolution TIFF file
```{r}
ggplot2::ggsave(final_plot,file = "call_latency_persite_figure3.tiff",
                device='tiff', dpi=800,  width = 297, 
                height = 210,  units = "mm")
```



